blueprint:
  name: Fire Hue Dimmer Switch Events
  domain: automation
  input:
    dimmer_switches:
      name: Dimmer Switches
      selector:
        device:
          filter:
            - manufacturer: Phillips
            - model: RWL020
          multiple: true
    target_event_name:
      name: Event Name
      selector:
        text:
    target_event_transition:
      name: Enable Transitions?
      selector:
        select:
          options:
            - Yes
            - No

trigger:
  - platform: event
    event_type: zha_event

variables:
  dimmer_switches: !input dimmer_switches
  dimmer_id: {{ trigger.event.data.device_id }}
  dimmer_button: {{ trigger.event.data.args.button }}
  dimmer_press_type: {{ trigger.event.data.args.press_type }}
  dimmer_command: {{ trigger.event.data.command }}
  event_action: {{ 'off' if trigger.event.data.args.button == 'off' else 'on' }}
  event_transition: >
    {% if trigger.event.data.args.button in ['off','on'] %}
      1
    {% else %}
      0.5
    {% endif %}

action:
  - event: 
    target: !input target_lights
    data: {{ action_data }}
      
