blueprint:
  name: Hue Dimmer Switch
  description: Configure Hue Dimmer Buttons
  domain: automation
  input:
    dimmer_switches:
      name: Dimmer Switches
      description: Dimmer Switches to configure
      selector:
        device:
          filter:
            - manufacturer: Phillips
            - model: RWL020
          multiple: true
    target_lights:
      name: Lights
      description: Lights to control
      selector:
        target:
          entity:
           domain: light
    light_profile:
      name: Light Profile
      description: Light Profile to set
      selector:
        select:
          options:
            - relax
            - concentrate
            - energize
            - reading

trigger_variables:
  dimmer_devices: !input dimmer_switches

trigger:
{% for device_id in states(dimmer_devices) %}
- platform: event
  event_type: zha_event
  event_data:
    device_id: {{ device_id }}
{% endfor %}

action: