blueprint:
  name: Hue Dimmer Switch
  description: Configure Hue Dimmer Buttons
  domain: automation
  input:
    dimmer_switches:
      name: Dimmer Switches
      description: Dimmer Switches to configure
      selector:
        device:
          filter:
            - manufacturer: Phillips
            - model: RWL020
          multiple: true
    target_lights:
      name: Lights
      description: Lights to control
      selector:
        target:
          entity:
           domain: light
    light_profile:
      name: Light Profile
      description: Light Profile to set
      selector:
        select:
          options:
            - relax
            - concentrate
            - energize
            - reading

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input dimmer_switches
    command: 'on'
  id: 'on'
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input dimmer_switches
    command: off_with_effect
  id: 'off'
- platform: event
  event_type: zha_event
  id: 'up'
  event_data:
    device_id: !input dimmer_switches
    command: step
    args:
    - 0
    - 30
    - 9
- platform: event
  event_type: zha_event
  id: 'down'
  event_data:
    device_id: !input dimmer_switches
    command: step
    args:
    - 1
    - 30
    - 9

action:
- choose:
  - conditions:
    - condition: trigger
      id: 'on'
    sequence:
    - service: light.turn_on
      target: !input target_lights
      data:
        profile: !input light_profile
        transition: 1
  - conditions:
    - condition: trigger
      id: 'off'
    sequence:
    - service: light.turn_off
      target: !input target_lights
      data:
        transition: 1
  - conditions:
    - condition: trigger
      id: 'down'
    sequence:
    - service: light.turn_on
      target: !input target_lights
      data:
        profile: !input light_profile
        brightness_step_pct: -5
        transition: 0.5
  - conditions:
    - condition: trigger
      id: 'up'
    sequence:
    - service: light.turn_on
      target: !input target_lights
      data:
        profile: !input light_profile
        brightness_step_pct: 5
        transition: 0.5
