blueprint:
  name: Hue Dimmer Switch
  description: Configure Hue Dimmer Buttons
  domain: automation
  input:
    dimmer_switch:
      name: Dimmer Switch
      description: Dimmer Switch to control
      selector:
        device:
          filter:
            - manufacturer: Phillips
            - model: RWL020
          entity:
            - domain: button
        multiple: true
    lights:
      name: Lights
      description: Lights to control
      selector:
        target:
          entity:
            filter:
              - domain: light

trigger:
  - platform: event
    event_type: zha_event


action:
