blueprint:
  name: Hue Dimmer Switch
  description: Configure Hue Dimmer Buttons
  domain: automation
  input:
    dimmer_switches:
      name: Dimmer Switches
      description: Dimmer Switches to configure
      selector:
        device:
          filter:
            - manufacturer: Phillips
            - model: RWL020
          entity:
            - domain: button
          multiple: true
    target_lights:
      name: Lights
      description: Lights to control
      selector:
        target:
          entity:
           domain: light
    light_profile:
      name: Light Profile
      description: Light Profile to set
      selector:
        select:
          options:
            - relax
            - concentrate
            - energize
            - reading

trigger:
- platform: event
  event_type: zha_event
  event_data:
    command: 'on'
  id: 'on'
  entity_id: !input dimmer_switches
- platform: event
  event_type: zha_event
  event_data:
    command: off_with_effect
  id: 'off'
  entity_id: !input dimmer_switches
- platform: event
  event_type: zha_event
  id: 'up'
  event_data:
    command: step
    args:
    - 0
    - 30
    - 9
  entity_id: !input dimmer_switches
- platform: event
  event_type: zha_event
  id: 'down'
  event_data:
    command: step
    args:
    - 1
    - 30
    - 9
  entity_id: !input dimmer_switches

action: